### ISSUE TITLE
Issue with custom layer

### ISSUE THREAD

**Issue by urbainvaes** [rmsrosa/ChainPlot.jl#12]
Many thanks for the nice package!

I am encountering the following issue when trying to plot a NN with a custom layer. While the following code works as expected
```julia
custom(x) = [x[1]^2, x[2]^2, x[3]]
nnx = Chain(custom, Dense(3,4), Dense(4,2))
plot(nnx, rand(3), title="$nna")
```
the following small modification of it does not:
```julia
custom(x) = [x[1]^2, x[2]^2, sin(x[3])]
nnx = Chain(custom, Dense(3,4), Dense(4,2))
plot(nnx, rand(3), title="$nna")
```
The latter code fails with error
```julia
ERROR: MethodError: no method matching sin(::ChainPlots.NeuralNumbers.NeuralNumber)
```
I tried to extend the function `sin` to NeuralNumbers, but the issue persisted, so any help would be much appreciated.

**EDIT**: Actually, the following line
```julia
Base.sin(x::ChainPlots.NeuralNumbers.NeuralNumber) = x
```
fixes the issue. It would be nice to have native support for `sin` and `cos`, though.

**Comment by musoke** [comment]
You may find some of the discussion in #10 helpful

**Comment by urbainvaes** [comment]
Indeed very useful, thank you very much!

**Comment by rmsrosa** [comment]
Thanks, I just need to add support for more math functions
